### ISSUE TITLE
exclude mootool core

### ISSUE THREAD

**Issue by ghost** [anutron/mootools-depender#2]
this results in

//Contents: Core, More, Array, String, Function, Number, Hash, Class, Class.Refactor blar blar

ie I exclude mootools core I build but I get mootools core;

**Comment by anutron** [comment]
was this using the php version? can you include the entire header (the url you used)?

**Comment by ghost** [comment]
yeah soz did that a bit quick with no info; yep php

excludeLibs=mootools-core&requireLibs=mootools-more&excludeLibs=clientcide&excludeLibs=depender-client

**Comment by anutron** [comment]
ok, so the issue here is you define the excludeLibs value several times, and it's only using the last one. If you're using the PHP version, you can do either of these things:

excludeLibs=foo,bar
excludeLibs[]=foo&excludeLibs[]=bar

Did you author this url yourself, or did you use the UI to get it? If so, then the bug is in the UI.
